// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

#nullable disable

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20230818232827_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "Acadia features the tallest mountain on the Atlantic coast of the United States, granite peaks, ocean shoreline, woodlands, and lakes.",
                            Name = "Acadia National Park",
                            State = "Maine",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "The southernmost national park is on three Samoan islands in the South Pacific. It protects coral reefs, rainforests, volcanic mountains, and white beaches.",
                            Name = "American Samoa",
                            State = "American Samoa",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "This site features more than 2,000 natural sandstone arches.",
                            Name = "Arches National Park",
                            State = "Utah",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "They contain the largest known assemblage of late Eocene and Oligocene mammal fossils.",
                            Name = "Badlands National Park",
                            State = "South Dakota",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "Its main attraction is backcountry recreation in the arid Chisos Mountains and in canyons along the river",
                            Name = "Big Bend National Park",
                            State = "Texas",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "A remote oasis catering to camping and boating on the shore of a scenic desert canyon reservoir.",
                            Name = "Lake Owyhee State Park",
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 7,
                            Description = "Hat Rock is a geological formation that, along with another outcropping rock in the park called Boat Rock, are thought to be exposed remnants of a 12-million-year-old basalt flow.",
                            Name = "Hat Rock State Park",
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 8,
                            Description = "Tumalo State Park is located in the Deschutes River canyon, running along both sides of the river.",
                            Name = "Tumalo State Park",
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 9,
                            Description = "It covers 1,842 acres (7.45 km2) of land around 1,759-foot (536 m) Humbug Mountain, one of the tallest headlands on the Oregon coast.",
                            Name = "Humbug Mountain State Park",
                            State = "Oregon",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 10,
                            Description = "Cape Blanco extends farther west than any point of land in the contiguous United States (lower 48 states) except portions of the Olympic Peninsula in Washington.",
                            Name = "Cape Blanco State Park",
                            State = "Oregon",
                            Type = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
